plugins {
    id("com.hayden.testgraphsdk.graph")
}

/**
 * skt validation graphs.
 *
 * WHY THIS EXISTS AT ALL
 * ----------------------
 * This repository ships the `skt` plugin — a CLI, two shell hooks, and an
 * install script — and until ARTI-19 it had no test_graph project, so its
 * behaviour was unreachable from any validation graph in the fleet. What it
 * did have is a 100-test pytest suite, and the suite is not the thing that is
 * missing: every one of those tests imports `skt.*` and calls a function.
 *
 * So this graph deliberately asserts the things an import CANNOT reach:
 *
 *   skt.wrapper-installed            skill-scripts/install-skt.sh really runs,
 *       on each PINNED interpreter, and the wrapper it writes answers with no
 *       python on PATH. `requires-python = ">=3.11"` is a claim until
 *       something executes on the floor; the matrix is what makes it a
 *       measurement, and it is the same 3.11/3.13 pair CI runs pytest on.
 *
 *   skt.status-tiers                 three REAL checkouts — an operator root,
 *       a main working tree, and a linked worktree of it — and `skt status`
 *       naming the right tier for each. The distinction is git plumbing
 *       (`--git-dir` vs `--git-common-dir`), so nothing short of a real
 *       linked worktree exercises it. Also: units, plugins, policy, the drift
 *       gate, ticket/epic/spec context, and the checkout kind.
 *
 *   skt.check-cached-costs-one-read  the PostToolUse budget, measured. That
 *       hook gets 2 SECONDS per tool call, and what makes that survivable is
 *       that `--cached` is contract-cache-only. Driven in-process on each
 *       pinned interpreter under CPython's audit hook AND a poisoned
 *       subprocess, os.spawn, fork and ThreadPoolExecutor surface, across all
 *       five cache states plus the corrupt-record fold — with two CONTROLS on
 *       the same run proving both instruments fire when there IS a spawn.
 *
 *   skt.hook-contract                what the two shipped hooks leave on
 *       disk. One hook.log line per SessionStart, exit 0 even when `skt` is
 *       unresolvable, and PostToolUse injecting ONCE per check RESULT over
 *       five consecutive tool calls — the regression that was fixed in #22.
 *
 *   skt.ticket-roundtrip             `skt ticket new` -> `info` -> `close`
 *       against a real repository: a linked worktree appears, git knows about
 *       it, close removes the directory and KEEPS the branch. Plus the four
 *       refusal remedies, each of which must name a command that runs in the
 *       home it is printed for (#25).
 *
 * FOUR OF THE FIVE nodes reach skt only through the wrapper
 * `skt.wrapper-installed` built — as a subprocess, never as an import. A graph
 * that imported `skt.cli` would be a slower copy of the pytest suite, which is
 * the degenerate outcome test-graph exists to prevent.
 *
 * skt.check-cached-costs-one-read is the ONE exception, and it has to be. Its
 * claim is "this code path creates no process and opens exactly one file", and
 * the two instruments that can establish that — `sys.addaudithook` and a
 * poisoned subprocess / os.spawn / fork / ThreadPoolExecutor surface — exist
 * only INSIDE the interpreter running the code. Measured from outside, all a
 * subprocess offers is its wall time, and wall time is exactly the evidence
 * that passes on an idle laptop and fails on a loaded runner while measuring
 * neither the spawn nor the read. So `support/cached_no_spawn_probe.py`
 * imports `skt.check` on the pinned interpreter and drives it in-process, and
 * the node's own docstring says so. It is a different KIND of evidence from
 * the other four, not a cheaper version of it.
 *
 * DEPENDENCIES are declared at SCRIPT level (`NodeSpec.depends_on`), so each
 * assertion node still stands on its own outside this graph. What gates in
 * practice is the harness fail-fast plus those edges — see
 * docs/sktSurface.dot, which is GENERATED by the test-graph skill's
 * discover.py and must never be hand-edited.
 *
 * Run:
 *   <test-graph-skill>/scripts/discover.py sktSurface
 *   <test-graph-skill>/scripts/run.py sktSurface
 */
validationGraph {
    sourcesDir("sources")

    testGraph("sktSurface") {
        // FIRST, and the only node with no upstream: it builds the wrapper
        // every other node calls. Its failure is a precondition failure, and
        // the harness fail-fast skips the rest rather than reporting four
        // downstream failures for one missing interpreter.
        node("sources/skt_wrapper_installed.py")
        node("sources/skt_status_tiers.py")
        node("sources/skt_check_cached.py")
        node("sources/skt_hook_contract.py")
        node("sources/skt_ticket_roundtrip.py")
    }

    /*
     * sktHooks — the subset a hook change needs, and nothing else.
     *
     * The two nodes that decide whether a session is safe to run: the
     * PostToolUse cost claim and the two hooks' on-disk contract. Kept as its
     * own task because those are the nodes an agent editing hooks/ reruns,
     * and paying for the ticket round trip to see them is how people stop
     * rerunning graphs at all.
     */
    testGraph("sktHooks") {
        node("sources/skt_wrapper_installed.py")
        node("sources/skt_check_cached.py")
        node("sources/skt_hook_contract.py")
    }
}

/*
 * IMPORTING USER CODE
 * -------------------
 * Node scripts reach this repository at `../..` from `sources/`. Shared
 * fixture builders live in `../support/skt_fixture.py` and are imported with
 * an explicit sys.path insert — NOT from `sources/`, because the Gradle
 * plugin describes every script in a registered sourcesDir and a module with
 * no NodeSpec is not a node.
 *
 * `support/cached_no_spawn_probe.py` is stdlib-only on purpose: it is exec'd
 * by an absolute pinned interpreter, outside uv, so it cannot depend on
 * testgraphsdk.
 */
