[adapters.CreateAccount]
adapter = "specs.program_model.adapters:CreateAccountInternalAdapter"
kind = "ecommerce-internal"

[adapters.AddCartItem]
adapter = "specs.program_model.adapters:AddCartItemInternalAdapter"
kind = "ecommerce-internal"

[adapters.Checkout]
adapter = "specs.program_model.adapters:CheckoutInternalAdapter"
kind = "ecommerce-internal"

[adapters.ProjectOrder]
adapter = "specs.program_model.adapters:ProjectOrderInternalAdapter"
kind = "ecommerce-internal"
