#!/usr/bin/env python3
"""Generate Python spec-double artifacts from spec_manifest.yaml."""

from __future__ import annotations

import argparse
import keyword
import re
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from extract_spec_manifest import load_manifest, validate_manifest  # noqa: E402


def spec_sources(module: str, manifest_path: Path) -> list[str]:
    """Name the TLA+ files this manifest actually describes.

    The accepted baseline spreads semantics across Core/Internal/External; only
    a legacy spec has a single {module}.tla.
    """
    baseline = [
        name
        for name in ("Core.tla", "Internal.tla", "External.tla")
        if (manifest_path.parent / name).exists()
    ]
    if any(name == "Internal.tla" for name in baseline):
        return baseline
    return [f"{module}.tla"]


def header(module: str, manifest_path: Path) -> str:
    sources = "".join(f"#   - {name}\n" for name in spec_sources(module, manifest_path))
    return (
        "# Generated by Spec Double Compiler.\n"
        "# Source of truth:\n"
        f"{sources}"
        f"#   - {manifest_path.name}\n"
        "# Do not edit this file directly.\n"
        "# Extension points are marked explicitly.\n\n"
    )


def as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def class_names(manifest: dict[str, Any]) -> list[str]:
    names: list[str] = []
    names.extend(as_dict(manifest.get("types")).keys())
    names.extend(as_dict(manifest.get("state")).keys())
    names.extend(as_dict(manifest.get("commands")).keys())
    names.extend(as_dict(manifest.get("results")).keys())
    return names


def state_class(manifest: dict[str, Any]) -> str:
    states = list(as_dict(manifest.get("state")).keys())
    if not states:
        raise ValueError("manifest must define at least one state class")
    return states[0]


def fake_class(manifest: dict[str, Any]) -> str:
    fake = as_dict(manifest.get("fake"))
    return str(fake.get("class") or f"{manifest['module']}SpecDouble")


def command_to_method(manifest: dict[str, Any]) -> dict[str, str]:
    mapping: dict[str, str] = {}
    for port in as_dict(manifest.get("ports")).values():
        for method_name, method in as_dict(as_dict(port).get("methods")).items():
            command = as_dict(method).get("command")
            if command:
                mapping[str(command)] = str(method_name)
    return mapping


def command_result(manifest: dict[str, Any], command_name: str) -> str:
    for port in as_dict(manifest.get("ports")).values():
        for method in as_dict(as_dict(port).get("methods")).values():
            if as_dict(method).get("command") == command_name:
                return str(as_dict(method).get("result"))
    raise ValueError(f"no port method found for command {command_name}")


def py_default(value: Any) -> str:
    if value is None:
        return "None"
    return repr(value)


def render_types(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    lines = [header(module, manifest_path), "from dataclasses import dataclass\n\n"]

    for name, spec in as_dict(manifest.get("types")).items():
        lines.append(f"{name} = {as_dict(spec).get('python', 'str')}\n")
    if manifest.get("types"):
        lines.append("\n")

    for section in ["state", "commands", "results", "events"]:
        for class_name, spec in as_dict(manifest.get(section)).items():
            lines.append("@dataclass(frozen=True)\n")
            lines.append(f"class {class_name}:\n")
            fields = as_dict(as_dict(spec).get("fields"))
            if not fields:
                lines.append("    pass\n\n")
                continue
            for field_name, field_spec in fields.items():
                field = as_dict(field_spec)
                suffix = ""
                if "default" in field:
                    suffix = f" = {py_default(field['default'])}"
                lines.append(f"    {field_name}: {field.get('type', 'object')}{suffix}\n")
            lines.append("\n")
    return "".join(lines)


def render_ports(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    imports = ", ".join(class_names(manifest))
    lines = [
        header(module, manifest_path),
        "from typing import Protocol, runtime_checkable\n\n",
        f"from .types import {imports}\n\n\n",
    ]

    for port_name, port in as_dict(manifest.get("ports")).items():
        lines.append("@runtime_checkable\n")
        lines.append(f"class {port_name}(Protocol):\n")
        methods = as_dict(as_dict(port).get("methods"))
        if not methods:
            lines.append("    pass\n\n")
            continue
        for method_name, method_spec in methods.items():
            method = as_dict(method_spec)
            result = method.get("result", "object")
            command = method.get("command")
            if command:
                lines.append(f"    def {method_name}(self, command: {command}) -> {result}:\n")
            else:
                lines.append(f"    def {method_name}(self) -> {result}:\n")
            lines.append("        ...\n\n")
        lines.append("\n")
    return "".join(lines)


def render_fake(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    state = state_class(manifest)
    imports = ", ".join(class_names(manifest))
    fake = as_dict(manifest.get("fake"))
    action_specs = as_dict(fake.get("actions"))
    state_fields = list(as_dict(as_dict(manifest["state"])[state]).get("fields", {}).keys())
    lines = [
        header(module, manifest_path),
        f"from .types import {imports}\n\n\n",
        f"class {fake_class(manifest)}:\n",
        f"    def __init__(self, state: {state}):\n",
        "        self._state = state\n\n",
        f"    def snapshot(self) -> {state}:\n",
        "        return self._state\n\n",
    ]

    for command_name, method_name in command_to_method(manifest).items():
        result = command_result(manifest, command_name)
        action = as_dict(action_specs.get(method_name))
        lines.append(f"    def {method_name}(self, command: {command_name}) -> {result}:\n")
        if action.get("template") == "bounded_set_add":
            collection = action["state_field"]
            limits = action["limit_field"]
            owner = action["owner_command_field"]
            item = action["item_command_field"]
            reason = action.get("reject_reason", "REJECTED")
            lines.extend(
                [
                    f"        current = self._state.{collection}[command.{owner}]\n",
                    f"        limit = self._state.{limits}[command.{owner}]\n\n",
                    "        if len(current) >= limit:\n",
                    f"            return {result}(accepted=False, reason={reason!r})\n\n",
                    f"        new_{collection} = {{\n",
                    f"            **self._state.{collection},\n",
                    f"            command.{owner}: current | frozenset({{command.{item}}}),\n",
                    "        }\n",
                    f"        self._state = {state}(\n",
                ]
            )
            for field in state_fields:
                value = f"new_{collection}" if field == collection else f"self._state.{field}"
                lines.append(f"            {field}={value},\n")
            lines.extend(["        )\n", f"        return {result}(accepted=True)\n\n"])
        else:
            lines.append(
                "        raise NotImplementedError(\n"
                f"            \"No v0 fake template configured for {method_name}\"\n"
                "        )\n\n"
            )
    return "".join(lines)


def invariant_function_name(name: str) -> str:
    chars = []
    for char in name:
        if char.isupper() and chars:
            chars.append("_")
        chars.append(char.lower())
    candidate = "".join(chars).replace("__", "_")
    if keyword.iskeyword(candidate):
        return f"{candidate}_"
    return candidate


def to_snake(name: str) -> str:
    chars: list[str] = []
    for index, char in enumerate(name):
        if char.isupper() and index > 0:
            chars.append("_")
        chars.append(char.lower())
    return "".join(chars).replace("__", "_")


def render_validators(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    state = state_class(manifest)
    imports = ", ".join(class_names(manifest))
    invariant_templates = as_dict(manifest.get("invariant_templates"))
    actions = as_dict(as_dict(manifest.get("fake")).get("actions"))
    mapping = command_to_method(manifest)

    lines = [header(module, manifest_path), f"from .types import {imports}\n\n\n"]
    lines.append(f"def validate_state(state: {state}) -> None:\n")
    for invariant in manifest.get("invariants", []) or []:
        lines.append(f"    validate_{invariant_function_name(str(invariant))}(state)\n")
    if not manifest.get("invariants"):
        lines.append("    return None\n")
    lines.append("\n\n")

    lines.extend(
        [
            f"def explain_state_failure(state: {state}) -> str:\n",
            "    try:\n",
            "        validate_state(state)\n",
            "    except AssertionError as exc:\n",
            "        return str(exc)\n",
            "    return \"\"\n\n\n",
            "def explain_transition_failure(exc: AssertionError) -> str:\n",
            "    return str(exc)\n\n\n",
            f"def validate_trace(initial_state: {state}, commands: list[object], port: object) -> None:\n",
            "    validate_state(initial_state)\n",
            "    for command in commands:\n",
            "        before = port.snapshot()\n",
            "        method_name = command.__class__.__name__\n",
            "        if method_name not in _COMMAND_METHODS:\n",
            "            raise AssertionError(f\"no generated transition dispatcher for {method_name}\")\n",
            "        result = getattr(port, _COMMAND_METHODS[method_name])(command)\n",
            "        after = port.snapshot()\n",
            "        _validate_transition(before, command, result, after)\n\n\n",
        ]
    )

    for invariant in manifest.get("invariants", []) or []:
        name = str(invariant)
        spec = as_dict(invariant_templates.get(name))
        fn = invariant_function_name(name)
        lines.append(f"def validate_{fn}(state: {state}) -> None:\n")
        if spec.get("template") == "bounded_set_size":
            collection = spec["collection_field"]
            limits = spec["limit_field"]
            item_label = spec.get("item_label", "items")
            lines.extend(
                [
                    f"    for owner_id, items in state.{collection}.items():\n",
                    f"        limit = state.{limits}[owner_id]\n",
                    "        if len(items) > limit:\n",
                    "            raise AssertionError(\n",
                    f"                f\"{{owner_id}} owns {{len(items)}} {item_label}, but limit is {{limit}}\"\n",
                    "            )\n\n\n",
                ]
            )
        else:
            lines.append(f"    raise NotImplementedError(\"No invariant template configured for {name}\")\n\n\n")

    for command_name, method_name in mapping.items():
        action = as_dict(actions.get(method_name))
        result = command_result(manifest, command_name)
        lines.append(
            f"def validate_{method_name}_transition(\n"
            f"    before: {state},\n"
            f"    command: {command_name},\n"
            f"    result: {result},\n"
            f"    after: {state},\n"
            ") -> None:\n"
        )
        if action.get("template") == "bounded_set_add":
            collection = action["state_field"]
            limits = action["limit_field"]
            owner = action["owner_command_field"]
            item = action["item_command_field"]
            reason = action.get("reject_reason", "REJECTED")
            lines.extend(
                [
                    f"    current = before.{collection}[command.{owner}]\n",
                    f"    limit = before.{limits}[command.{owner}]\n\n",
                    "    if len(current) >= limit:\n",
                    "        assert not result.accepted\n",
                    f"        assert result.reason == {reason!r}\n",
                    "        assert after == before\n",
                    "        return\n\n",
                    "    assert result.accepted\n",
                    f"    assert command.{item} in after.{collection}[command.{owner}]\n",
                    "    validate_state(after)\n\n\n",
                ]
            )
        else:
            lines.append(f"    raise NotImplementedError(\"No transition template configured for {method_name}\")\n\n\n")

    lines.append("_COMMAND_METHODS = {\n")
    for command_name, method_name in mapping.items():
        lines.append(f"    {command_name!r}: {method_name!r},\n")
    lines.append("}\n\n\n")
    lines.append(f"def _validate_transition(before: {state}, command: object, result: object, after: {state}) -> None:\n")
    for command_name, method_name in mapping.items():
        lines.append(f"    if isinstance(command, {command_name}):\n")
        lines.append(f"        validate_{method_name}_transition(before, command, result, after)\n")
        lines.append("        return\n")
    lines.append("    raise AssertionError(f\"no transition validator for {command.__class__.__name__}\")\n")
    return "".join(lines)


def finite_values(manifest: dict[str, Any], source: str) -> Any:
    return as_dict(as_dict(manifest.get("finite_model")).get(source)).get("values", [])


def type_sources(manifest: dict[str, Any]) -> dict[str, str]:
    sources: dict[str, str] = {}
    for type_name, spec in as_dict(manifest.get("types")).items():
        source = as_dict(spec).get("source")
        if source:
            sources[str(type_name)] = str(source)
    return sources


def strategy_name_for_type(type_name: str) -> str:
    return f"{to_snake(type_name)}_strategy"


def parse_bounded_collection(type_expr: str) -> tuple[str, str] | None:
    match = re.fullmatch(r"dict\[(\w+),\s*frozenset\[(\w+)\]\]", type_expr.strip())
    if not match:
        return None
    return match.group(1), match.group(2)


def render_strategies(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    state = state_class(manifest)
    imports = ", ".join(class_names(manifest))
    state_fields = as_dict(as_dict(manifest["state"])[state]).get("fields", {})
    sources = type_sources(manifest)
    limits = as_dict(finite_values(manifest, "Limits"))
    generators = as_dict(manifest.get("generators"))
    max_depth = as_dict(generators.get("traces")).get("max_depth", 8)
    command_names = list(as_dict(manifest.get("commands")).keys())
    command_name = command_names[0] if command_names else "object"

    lines = [
        header(module, manifest_path),
        "try:\n",
        "    from hypothesis import strategies as st\n",
        "except Exception:  # pragma: no cover\n",
        "    st = None\n\n",
        f"from .types import {imports}\n\n\n",
        "def _require_hypothesis():\n",
        "    if st is None:\n",
        "        raise RuntimeError(\"Hypothesis is required for generated strategies\")\n\n\n",
    ]

    for type_name, source in sources.items():
        values = list(finite_values(manifest, source))
        lines.append(f"def {strategy_name_for_type(type_name)}():\n")
        lines.append("    _require_hypothesis()\n")
        lines.append(f"    return st.sampled_from({values!r})\n\n\n")

    owned_type = as_dict(state_fields.get("owned")).get("type")
    collection_types = parse_bounded_collection(str(owned_type)) if owned_type else None

    lines.append(f"def {to_snake(state)}_strategy():\n")
    lines.append("    _require_hypothesis()\n")

    if "owned" in state_fields and "limits" in state_fields and limits and collection_types:
        owner_type, item_type = collection_types
        users = list(finite_values(manifest, sources.get(owner_type, "")))
        item_strategy = strategy_name_for_type(item_type)
        lines.append(f"    return st.builds(\n        {state},\n")
        lines.append("        owned=st.fixed_dictionaries({\n")
        for user in users:
            lines.append(
                f"            {user!r}: st.sets({item_strategy}(), max_size={int(limits[user])}).map(frozenset),\n"
            )
        lines.append("        }),\n")
        lines.append(f"        limits=st.just({limits!r}),\n")
        lines.append("    )\n\n\n")
    else:
        lines.append(f"    raise NotImplementedError(\"No state strategy template configured for {state}\")\n\n\n")

    if command_names:
        command = as_dict(manifest["commands"][command_name])
        fields = as_dict(command.get("fields"))
        arg_lines = []
        for field_name, field in fields.items():
            field_type = as_dict(field).get("type")
            if field_type in sources:
                arg_lines.append(f"        {field_name}={strategy_name_for_type(str(field_type))}(),")
            else:
                arg_lines.append(f"        {field_name}=st.none(),")
        lines.append("def command_strategy():\n")
        lines.append("    _require_hypothesis()\n")
        lines.append(f"    return st.builds(\n        {command_name},\n")
        lines.extend(line + "\n" for line in arg_lines)
        lines.append("    )\n\n\n")
        lines.append("def valid_trace_strategy():\n")
        lines.append("    _require_hypothesis()\n")
        lines.append(f"    return st.lists(command_strategy(), max_size={int(max_depth)})\n\n\n")
        lines.append("def edge_case_strategy():\n")
        lines.append("    _require_hypothesis()\n")
        lines.append("    return command_strategy()\n")
    return "".join(lines)


def render_traces(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    imports = ", ".join(class_names(manifest))
    lines = [header(module, manifest_path), f"from .types import {imports}\n\n\n"]
    traces = as_dict(manifest.get("example_traces"))
    for trace_name, commands in traces.items():
        lines.append(f"{trace_name} = [\n")
        for command in commands or []:
            if not isinstance(command, dict) or len(command) != 1:
                continue
            command_name, fields = next(iter(command.items()))
            args = ", ".join(f"{k}={v!r}" for k, v in as_dict(fields).items())
            lines.append(f"    {command_name}({args}),\n")
        lines.append("]\n\n")
    return "".join(lines)


def render_contract_tests(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    state = state_class(manifest)
    imports = ", ".join(class_names(manifest))
    fake = fake_class(manifest)
    mapping = command_to_method(manifest)
    port_names = list(as_dict(manifest.get("ports")).keys())
    conformance_name = to_snake(port_names[0]) if port_names else str(manifest["package"])
    lines = [
        header(module, manifest_path),
        f"from .fake import {fake}\n",
        f"from .types import {imports}\n",
        "from .validators import _validate_transition\n\n\n",
        f"def assert_{conformance_name}_conformance(adapter_factory, initial_state: {state}, commands: list[object]) -> None:\n",
        f"    expected = {fake}(initial_state)\n",
        "    actual = adapter_factory(initial_state)\n\n",
        "    for command in commands:\n",
        "        before = actual.snapshot()\n",
        "        method_name = _command_to_method(command)\n",
        "        expected_result = getattr(expected, method_name)(command)\n",
        "        actual_result = getattr(actual, method_name)(command)\n",
        "        after = actual.snapshot()\n",
        "        assert actual_result == expected_result\n",
        "        _validate_transition(before, command, actual_result, after)\n\n\n",
        "def _command_to_method(command: object) -> str:\n",
    ]
    for command_name, method_name in mapping.items():
        lines.append(f"    if isinstance(command, {command_name}):\n")
        lines.append(f"        return {method_name!r}\n")
    lines.append("    raise AssertionError(f\"no method mapping for {command.__class__.__name__}\")\n")
    return "".join(lines)


# ---------------------------------------------------------------------------
# Effect providers: content assertion is the DEFAULT, and the alternative is loud.
#
# Measured and replicated: content-asserting effect providers caught 2 of 6
# seeded faults that nothing else caught, reproduced cell for cell across two
# rounds, then replicated by a blind agent on a fresh 16-mutant catalogue at
# 3 of 3 durable-write mutants under the checking mapping and 0 of 3 under the
# silent one. That is 30% of the instrument's entire yield riding on a mapping
# line -- and until HP-05 the scaffold shipped a `raise NotImplementedError`
# stub and a COMMENTED-OUT binding, so the author wrote the provider, and the
# one a hurried author writes is the silent one. A round-2 blind agent did
# exactly that and did not notice until afterwards.
#
# So codegen now emits the content-asserting provider and binds it. Nothing
# here refuses anything: an unbound port, a silent provider and a port with no
# content declaration are all allowed, and all three are ANNOUNCED, because
# their kills are a floor and a green run under them over-reads.
# ---------------------------------------------------------------------------

DURABLE_WRITE = "durable_write"

#: The one sentence every instrument without a durable-write oracle must emit.
#: Kept as a constant so the provider announcement, the codegen audit and the
#: reference page cannot drift apart.
NO_ORACLE_SENTENCE = (
    "Nothing compares what crossed this port against the model, so kills "
    "counted under this mapping are a FLOOR, not a total, and a green run "
    "over-reads."
)

ANNOUNCE_PREFIX = "[effect-mapping]"


def effect_ports(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Semantic effect ports: the ones a provider can be bound to (EP-01)."""
    return {
        str(name): as_dict(spec)
        for name, spec in as_dict(manifest.get("ports")).items()
        if as_dict(spec).get("role") == "effect"
    }


def declared_effect_boundaries(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Ports declared under `effects:` for passive observation (MF-013).

    A boundary may be declared here and carry no provider at all. That is the
    exact shape the audit exists to report: a project can say "this is a
    durable write" and still run with nothing reading the bytes.
    """
    found: dict[str, dict[str, Any]] = {}
    for component in as_dict(as_dict(manifest.get("effects")).get("components")).values():
        for name, spec in as_dict(as_dict(component).get("ports")).items():
            found[str(name)] = as_dict(spec)
    return found


def port_content_spec(port: dict[str, Any]) -> dict[str, dict[str, str]]:
    """`content:` -- per method, which payload field equals which modeled value.

    Two productions, deliberately: `variable` and `variable[payload_field]`.
    A durable write is only checkable against the model when somebody says what
    it refines; this is that sentence, and it is the smallest one that kills a
    stale running total.
    """
    spec: dict[str, dict[str, str]] = {}
    for method_name, fields in as_dict(port.get("content")).items():
        rendered = {str(field): str(expression) for field, expression in as_dict(fields).items()}
        if rendered:
            spec[str(method_name)] = rendered
    return spec


def provider_symbol(port_name: str) -> str:
    return f"{to_snake(port_name)}_provider"


def silent_provider_symbol(port_name: str) -> str:
    return f"silent_{to_snake(port_name)}_provider"


def default_result_expression(result: str) -> str:
    return {
        "str": '""',
        "int": "0",
        "float": "0.0",
        "bool": "True",
        "bytes": 'b""',
        "None": "None",
    }.get(result.strip(), "None")


def render_effect_providers(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    ports = effect_ports(manifest)
    boundaries = declared_effect_boundaries(manifest)
    lines = [
        header(module, manifest_path),
        '"""Generated effect providers. CONTENT ASSERTION IS THE DEFAULT.\n\n',
        "Two providers per semantic effect port, and shipping two is the point:\n",
        "the checking one is bound by the generated default mapping, and the\n",
        "silent one exists so that choosing it is a VISIBLE edit to a mapping\n",
        "file rather than an assertion somebody quietly did not write.\n\n",
        "Neither suppresses anything. There is no flag that turns the checking\n",
        "provider's assertions off -- a suppression key would have been the\n",
        "shorter route and the wrong one, because a reader of a kill number has\n",
        "to be able to see which instrument produced it.\n\n",
        "Nothing here refuses to run. Every degraded configuration is announced\n",
        "on stdout the first time it binds, and the run proceeds.\n",
        '"""\n\n',
        "from __future__ import annotations\n\n",
        "import dataclasses\n",
        "import os\n",
        "import sys\n",
        "from contextlib import contextmanager\n",
        "from collections.abc import Iterator\n",
        "from typing import Any\n\n",
        f"from .types import {', '.join(class_names(manifest))}\n\n\n",
        f"NO_ORACLE_SENTENCE = {NO_ORACLE_SENTENCE!r}\n",
        f"ANNOUNCE_PREFIX = {ANNOUNCE_PREFIX!r}\n\n",
        "#: port -> method -> payload field -> modeled value it must equal.\n",
        "CONTENT_ASSERTIONS: dict[str, dict[str, dict[str, str]]] = {\n",
    ]
    for port_name, port in ports.items():
        lines.append(f"    {port_name!r}: {port_content_spec(port)!r},\n")
    lines.append("}\n\n")

    lines.append("#: port -> declared boundary kind, from `ports:` or `effects:`.\n")
    lines.append("PORT_KINDS: dict[str, str] = {\n")
    for port_name, port in ports.items():
        kind = port.get("kind") or boundaries.get(port_name, {}).get("kind") or "effect"
        lines.append(f"    {port_name!r}: {str(kind)!r},\n")
    lines.append("}\n\n")

    lines.append("#: Boundaries declared under `effects:` that no provider can be bound to.\n")
    lines.append("#: They are reported, never repaired -- a declaration without a seam is a\n")
    lines.append("#: finding for the project, not something codegen may invent a port for.\n")
    unbindable = {
        name: str(spec.get("kind") or "effect")
        for name, spec in boundaries.items()
        if name not in ports
    }
    lines.append(f"UNBOUND_DECLARED_BOUNDARIES: dict[str, str] = {unbindable!r}\n\n\n")

    lines.extend(_effect_provider_runtime())

    for port_name, port in ports.items():
        methods = as_dict(port.get("methods"))
        lines.append(f"class Recording{port_name}:\n")
        lines.append(
            f'    """The bound {port_name}. Every crossing is recorded so the model can judge it."""\n\n'
        )
        lines.append("    def __init__(self) -> None:\n")
        lines.append("        self.crossings: list[EffectCrossing] = []\n\n")
        if not methods:
            lines.append("    pass\n\n")
        for method_name, method_spec in methods.items():
            method = as_dict(method_spec)
            result = str(method.get("result", "object"))
            command = method.get("command")
            signature = f"self, command: {command}" if command else "self"
            lines.append(f"    def {method_name}({signature}) -> {result}:\n")
            if command:
                lines.append(
                    f"        self.crossings.append(EffectCrossing({port_name!r}, {method_name!r}, _payload(command)))\n"
                )
            else:
                lines.append(
                    f"        self.crossings.append(EffectCrossing({port_name!r}, {method_name!r}, {{}}))\n"
                )
            lines.append(f"        return {default_result_expression(result)}\n\n")
        lines.append("\n")

        lines.append(f"class ContentAsserting{port_name}Provider:\n")
        lines.append(
            f'    """THE DEFAULT for {port_name}. Asserts the payload against the modeled after-state."""\n\n'
        )
        lines.append(f"    port_name = {port_name!r}\n")
        lines.append("    asserts_content = True\n\n")
        lines.append("    @contextmanager\n")
        lines.append("    def bind(self, context: Any) -> Iterator[Any]:\n")
        lines.append(f"        binding = Recording{port_name}()\n")
        lines.append(f"        announce_binding({port_name!r}, _reference(self), asserts_content=True)\n")
        lines.append("        yield binding\n")
        lines.append(f"        assert_content({port_name!r}, binding.crossings, context)\n\n\n")

        lines.append(f"class Silent{port_name}Provider:\n")
        lines.append(
            f'    """The alternative for {port_name}, and it is LOUD. Binds, asserts nothing."""\n\n'
        )
        lines.append(f"    port_name = {port_name!r}\n")
        lines.append("    asserts_content = False\n\n")
        lines.append("    @contextmanager\n")
        lines.append("    def bind(self, context: Any) -> Iterator[Any]:\n")
        lines.append(f"        binding = Recording{port_name}()\n")
        lines.append(f"        announce_binding({port_name!r}, _reference(self), asserts_content=False)\n")
        lines.append("        yield binding\n\n\n")

    for port_name in ports:
        lines.append(f"{provider_symbol(port_name)} = ContentAsserting{port_name}Provider()\n")
        lines.append(f"{silent_provider_symbol(port_name)} = Silent{port_name}Provider()\n")
    if ports:
        lines.append("\n")

    package = str(manifest["package"])
    lines.append("#: The default mapping codegen writes. Content-asserting, every port.\n")
    lines.append("DEFAULT_PROVIDERS: dict[str, str] = {\n")
    for port_name in ports:
        lines.append(f"    {port_name!r}: {f'{package}.effect_providers:{provider_symbol(port_name)}'!r},\n")
    lines.append("}\n\n")
    lines.append("#: The declared way to run without a durable-write oracle, so that\n")
    lines.append("#: choosing it is an edit a reviewer can see.\n")
    lines.append("SILENT_PROVIDERS: dict[str, str] = {\n")
    for port_name in ports:
        lines.append(
            f"    {port_name!r}: {f'{package}.effect_providers:{silent_provider_symbol(port_name)}'!r},\n"
        )
    lines.append("}\n")
    return "".join(lines)


def _effect_provider_runtime() -> list[str]:
    """The port-independent half of the generated module, verbatim."""
    return [
        '@dataclasses.dataclass(frozen=True)\n',
        "class EffectCrossing:\n",
        "    port: str\n",
        "    method: str\n",
        "    payload: dict\n\n\n",
        "def _payload(command: Any) -> dict:\n",
        "    if dataclasses.is_dataclass(command):\n",
        "        return {field.name: getattr(command, field.name) for field in dataclasses.fields(command)}\n",
        "    if isinstance(command, dict):\n",
        "        return dict(command)\n",
        "    return {'value': command}\n\n\n",
        "def _reference(provider: Any) -> str:\n",
        "    return f'{type(provider).__module__}:{type(provider).__name__}'\n\n\n",
        "def mapping_name() -> str:\n",
        '    """Which mapping produced these numbers.\n\n',
        "    The framework does not hand a provider its mapping path, so this reads\n",
        "    the run's own invocation. It is a hint, not a contract, and it says so\n",
        "    when it cannot tell -- an unnamed mapping is itself worth announcing.\n",
        '    """\n',
        "    named = os.environ.get('TLA_SPEC_DEV_MAPPING')\n",
        "    if named:\n",
        "        return named\n",
        "    argv = list(sys.argv)\n",
        "    for index, token in enumerate(argv):\n",
        "        if token == '--mapping' and index + 1 < len(argv):\n",
        "            return argv[index + 1]\n",
        "        if token.startswith('--mapping='):\n",
        "            return token.split('=', 1)[1]\n",
        "    return '<unnamed mapping: set TLA_SPEC_DEV_MAPPING to name it>'\n\n\n",
        "_ANNOUNCED: set = set()\n\n\n",
        "def announce_binding(port: str, reference: str, *, asserts_content: bool) -> None:\n",
        '    """Say which instrument this is, once per port per process, unprompted."""\n',
        "    mapping = mapping_name()\n",
        "    key = (port, reference, mapping, asserts_content)\n",
        "    if key in _ANNOUNCED:\n",
        "        return\n",
        "    _ANNOUNCED.add(key)\n",
        "    for line in describe_binding(port, reference, mapping, asserts_content=asserts_content):\n",
        "        print(line, flush=True)\n\n\n",
        "def describe_binding(port: str, reference: str, mapping: str, *, asserts_content: bool) -> list[str]:\n",
        "    kind = PORT_KINDS.get(port, 'effect')\n",
        "    fields = sorted(\n",
        "        f'{method}.{field} == {expression}'\n",
        "        for method, spec in CONTENT_ASSERTIONS.get(port, {}).items()\n",
        "        for field, expression in spec.items()\n",
        "    )\n",
        "    if asserts_content and fields:\n",
        "        return [\n",
        "            f'{ANNOUNCE_PREFIX} DURABLE-WRITE ORACLE ACTIVE: {port} (kind: {kind}) is bound to '\n",
        "            f'{reference} under mapping {mapping}, asserting ' + str(len(fields)) + ' content field(s) '\n",
        "            f'against the modeled after-state: ' + '; '.join(fields),\n",
        "        ]\n",
        "    if asserts_content:\n",
        "        return [\n",
        "            f'{ANNOUNCE_PREFIX} NO DURABLE-WRITE ORACLE: {port} (kind: {kind}) is bound to '\n",
        "            f'{reference} under mapping {mapping}, which records every crossing but declares no '\n",
        "            f'`content:` block, so no payload field is compared to anything. ' + NO_ORACLE_SENTENCE,\n",
        "        ]\n",
        "    return [\n",
        "        f'{ANNOUNCE_PREFIX} NO DURABLE-WRITE ORACLE: {port} (kind: {kind}) is bound to the SILENT '\n",
        "        f'provider {reference} under mapping {mapping}. ' + NO_ORACLE_SENTENCE,\n",
        "    ]\n\n\n",
        "def _after(case: Any) -> Any:\n",
        "    after = getattr(case, 'after', None)\n",
        "    return {} if after is None else after\n\n\n",
        "def _lookup(container: Any, key: Any) -> Any:\n",
        "    try:\n",
        "        return container[key]\n",
        "    except (TypeError, KeyError, IndexError):\n",
        "        return getattr(container, str(key))\n\n\n",
        "def resolve(expression: str, after: Any, payload: dict) -> Any:\n",
        '    """`variable` or `variable[payload_field]`, evaluated against the after-state."""\n',
        "    name, bracket, rest = expression.partition('[')\n",
        "    value = _lookup(after, name.strip())\n",
        "    if bracket:\n",
        "        field = rest.rstrip(']').strip()\n",
        "        if field not in payload:\n",
        "            raise AssertionError(\n",
        "                f'content assertion {expression!r} indexes by payload field {field!r}, '\n",
        "                f'which this crossing does not carry: {sorted(payload)}'\n",
        "            )\n",
        "        value = _lookup(value, payload[field])\n",
        "    return value\n\n\n",
        "def assert_content(port: str, crossings: list, context: Any) -> None:\n",
        '    """Compare what crossed the boundary with what the model says is true after.\n\n',
        "    A durable write is the one thing an after-state comparison structurally\n",
        "    cannot see: the in-memory projection can be perfect while the persisted\n",
        "    bytes are wrong. This is the check that sees it.\n",
        '    """\n',
        "    spec = CONTENT_ASSERTIONS.get(port) or {}\n",
        "    if not spec:\n",
        "        return\n",
        "    after = _after(getattr(context, 'case', None))\n",
        "    for crossing in crossings:\n",
        "        for field, expression in spec.get(crossing.method, {}).items():\n",
        "            if field not in crossing.payload:\n",
        "                raise AssertionError(\n",
        "                    f'DETECTOR[provider_content_assertion] {port}.{crossing.method} declares a content '\n",
        "                    f'assertion on {field!r}, which the crossing does not carry: {sorted(crossing.payload)}'\n",
        "                )\n",
        "            observed = crossing.payload[field]\n",
        "            expected = resolve(expression, after, crossing.payload)\n",
        "            if observed != expected:\n",
        "                raise AssertionError(\n",
        "                    f'DETECTOR[provider_content_assertion] {port}.{crossing.method} wrote {field}='\n",
        "                    f'{observed!r} but the model says {expression} == {expected!r} '\n",
        "                    f'(action={getattr(context, \"action\", None)!r}, '\n",
        "                    f'case={getattr(getattr(context, \"case\", None), \"name\", None)!r})'\n",
        "                )\n\n\n",
    ]


def render_docs(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    lines = [
        f"# {module} Spec Double\n\n",
        "Generated by Spec Double Compiler.\n\n",
        "Source of truth:\n\n",
        *[f"- TLA+ module: `{name}`\n" for name in spec_sources(module, manifest_path)],
        f"- Manifest: `{manifest_path.name}`\n\n",
        "Do not edit generated files directly.\n\n",
        "## Ports\n\n",
    ]
    for port_name, port in as_dict(manifest.get("ports")).items():
        lines.append(f"- `{port_name}`: {', '.join(as_dict(as_dict(port).get('methods')).keys())}\n")
    lines.append("\n## Commands\n\n")
    for command_name in as_dict(manifest.get("commands")):
        lines.append(f"- `{command_name}`\n")
    lines.append("\n## Results\n\n")
    for result_name in as_dict(manifest.get("results")):
        lines.append(f"- `{result_name}`\n")
    lines.append("\n## Invariants\n\n")
    for invariant in manifest.get("invariants", []) or []:
        lines.append(f"- `{invariant}`\n")
    lines.append("\n## Adapter Mappings\n\n")
    lines.append("Keep refinement mappings outside generated files and review them as first-class contract artifacts.\n")
    return "".join(lines)


def render_init(manifest: dict[str, Any], manifest_path: Path) -> str:
    module = str(manifest["module"])
    return header(module, manifest_path) + "from .types import *  # noqa: F403\nfrom .ports import *  # noqa: F403\nfrom .fake import " + fake_class(manifest) + "\n"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def generate(manifest_path: Path, out_dir: Path) -> Path:
    manifest = load_manifest(manifest_path)
    errors = validate_manifest(manifest, manifest_path)
    if errors:
        raise SystemExit("\n".join(f"ERROR: {error}" for error in errors))

    package_dir = out_dir / str(manifest["package"])
    files = {
        "__init__.py": render_init(manifest, manifest_path),
        "types.py": render_types(manifest, manifest_path),
        "ports.py": render_ports(manifest, manifest_path),
        "fake.py": render_fake(manifest, manifest_path),
        "validators.py": render_validators(manifest, manifest_path),
        "strategies.py": render_strategies(manifest, manifest_path),
        "traces.py": render_traces(manifest, manifest_path),
        "contract_tests.py": render_contract_tests(manifest, manifest_path),
        "docs.md": render_docs(manifest, manifest_path),
    }
    for filename, content in files.items():
        write(package_dir / filename, content)
    return package_dir


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    package_dir = generate(args.manifest, args.out)
    print(f"generated {package_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
